go back to triggering releases by pushing tags

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,16 +1,13 @@
 name: Automatically create release
 
 on:
-  pull_request:
-    types:
-      - closed
-    branches:
-      - main
+  push:
+    tags:
+      - "v*"
 
 jobs:
   release:
     runs-on: ubuntu-latest
-    if: startsWith(github.event.pull_request.title, 'Release:') && startsWith(github.head_ref, 'release/')
     permissions:
       contents: write
     steps:
@@ -23,6 +20,21 @@ jobs:
           git config --global --add safe.directory "$GITHUB_WORKSPACE"
           git config user.name 'github-actions[bot]'
           git config user.email 'github-actions[bot]@users.noreply.github.com'
+
+      # Get new version
+      - name: Get new version number
+        id: get_new_version
+        uses: ./.github/actions/get-release-version
+        with:
+          file: ./rub-kunstgeschichte/rub-kunstgeschichte.dtx
+          class-name: rub-kunstgeschichte
+
+      # Check that the version number in the code and the one of the git tag match
+      - name: Check version number
+        if: ${{ github.ref }} != ${{ steps.get_new_version.outputs.version }}
+        run: |
+          echo "::error title={Version numbers don't match!}::{The version number of the git tag does not match the one in the code.}"
+          exit 1
 
       # Run automated testing
       # extract files from dtx
@@ -37,34 +49,15 @@ jobs:
             cd /workspace
             l3build ctan -q -H
 
-      # Get new version
-      - name: Get new version number
-        id: get_new_version
-        uses: ./.github/actions/get-release-version
-        with:
-          file: ./rub-kunstgeschichte/rub-kunstgeschichte.dtx
-          class-name: rub-kunstgeschichte
-
       # Extract release notes from CHANGELOG.md
       - name: Extract release notes
         id: extract_release_notes
         run: sed -n '/^## \[v0.2.0\]/,/^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\]/ { /^## \[v[0-9]\+\.[0-9]\+\.[0-9]\+\]/ !p; }' CHANGELOG.md | tee release_notes.md
 
-      # Tag new version
-      - name: Tag the commit
-        id: tag_commit
-        run: |
-          next_version=${{ steps.get_new_version.outputs.version }}
-          tag_name=v$next_version
-          git tag -a "$tag_name" -m "Version $next_version."
-          git push --follow-tags
-          echo "tag-name=$tag_name" >> "$GITHUB_OUTPUT"
-
       # Create a GitHub release
       - name: Release
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: ${{ steps.tag_commit.outputs.tag-name }}
           name: Release ${{ steps.get_new_version.outputs.version }}
           body_path: ./release_notes.md
           files: |
